#!/system/bin/sh
# set library path
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:'/data/click/lib'
export PATH=$PATH:'/data/click/bin'
export CLICKPATH="/data/click"
# execute the rest of the program
click $*
